// Standard default themes 
themes = [
  { 
    name: "ScreamOfTomato",
    backgroundColor: "aliceblue",
    textColor: "#666",
    textBackgroundColor: "aliceblue",
    activeTintColor: "tomato",
    inactiveTintColor: "gray",
    activeBackgroundColor: 'whitesmoke',
    inactiveBackgroundColor: 'lightgray',
    iconColor: "#666",
    headerBackgroundColor: "white",
    headerTintColor: "gray",
    bannerColor: "tomato",
    bannerFontFamily: "Lobster-Regular",
    borderColor: "#ccc",
    sectionBackgroundColor: "lightblue",
    rowColor: "#666",
    rowBackgroundColor: "aliceblue",
    selectedColor: "tomato",
    selectedBackgroundColor: "antiquewhite",
    menuListIconColor: "#999",
  },
  { 
    name: "DarkHedge",
    backgroundColor: "#666",
    textColor: "honeydew",
    textBackgroundColor: "#666",
    activeTintColor: "lime",
    activeBackgroundColor: 'darkgray',
    inactiveTintColor: "lightgray",
    inactiveBackgroundColor: 'gray',
    iconColor: "honeydew",
    headerBackgroundColor: "darkgray",
    headerTintColor: "lightgray",
    bannerColor: "lime",
    bannerFontFamily: "MuseoModerno-Regular",
    borderColor: "honeydew",
    sectionBackgroundColor: "darkslategray",
    rowColor: "honeydew",
    rowBackgroundColor: "#666",
    selectedColor: "lime",
    selectedBackgroundColor: "green",
    menuListIconColor: "lightgray",
  },
  { 
    name: "BananaRepublic",
    backgroundColor: "papayawhip",
    textColor: "brown",
    textBackgroundColor: "papayawhip",
    activeTintColor: "yellow",
    activeBackgroundColor: 'orange',
    inactiveTintColor: "gray",
    inactiveBackgroundColor: 'tan',
    iconColor: "brown",
    headerBackgroundColor: "white",
    headerTintColor: "gray",
    bannerColor: "orange",
    bannerFontFamily: "Bananas-Regular",
    borderColor: "brown",
    sectionBackgroundColor: "orange",
    rowColor: "brown",
    rowBackgroundColor: "papayawhip",
    selectedColor: "saddlebrown",
    selectedBackgroundColor: "wheat",
    menuListIconColor: "#999",
  },
  { 
    name: "ComeSeFosseAntani",
    backgroundColor: "ivory",
    textColor: "darkgreen",
    textBackgroundColor: "ivory",
    activeTintColor: "red",
    activeBackgroundColor: 'ivory',
    inactiveTintColor: "gray",
    inactiveBackgroundColor: 'khaki',
    iconColor: "darkgreen",
    headerBackgroundColor: "white",
    headerTintColor: "gray",
    bannerColor: "green",
    bannerFontFamily: "Italianno-Regular",
    borderColor: "darkgreen",
    sectionBackgroundColor: "linen",
    rowColor: "darkgreen",
    rowBackgroundColor: "ivory",
    selectedColor: "white",
    selectedBackgroundColor: "red",
    menuListIconColor: "#999",
  },
]

export default themes
